version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: vigovia-backend
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
    networks:
      - vigovia-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend/VigovioFullstack
      dockerfile: Dockerfile
    container_name: vigovia-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - vigovia-network
    restart: unless-stopped

networks:
  vigovia-network:
    driver: bridge
